services:
  - type: web
    name: thrive-throughit
    env: node
    region: oregon
    branch: main
    plan: free
    buildCommand: "npm run build:all && npm run migrate"
    startCommand: "npm run start:server"
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: WS_CORS_ORIGIN
        sync: false
